### ISSUE TITLE
Audio Manager Bug

### ISSUE THREAD

**Issue by Sherif-2001** [ufrshubham/flame_simple_platformer#2]
## When I play sound effects multiple times the app crashes and give me this error
![Screenshot (338)](https://user-images.githubusercontent.com/93449171/193216353-e6b1b948-d28b-4286-90fa-e5edb18bf4bd.png)

**Comment by ufrshubham** [comment]
@Sherif-2001 Is this something specific to `flame_simple_platformer` or is it happening for any other project as well?

**Comment by ufrshubham** [comment]
Seems like an issue from the `audioplayers` package with multiple similar issues reported:
- https://github.com/bluefireteam/audioplayers/issues/1290
- https://github.com/bluefireteam/audioplayers/issues/1274
- https://github.com/bluefireteam/audioplayers/issues/1260

Closing this because I don't think there is anything that `flame_simple_platformer` can do to solve this.

**Comment by Sherif-2001** [comment]
> @Sherif-2001 Is this something specific to `flame_simple_platformer` or is it happening for any other project as well?

For all projects

**Comment by Sherif-2001** [comment]
> Seems like an issue from the `audioplayers` package with multiple similar issues reported:
> 
> * [App crashes when I play multiple sounds bluefireteam/audioplayers#1290](https://github.com/bluefireteam/audioplayers/issues/1290)
> * [Crash on Android Error: java.util.ConcurrentModificationException bluefireteam/audioplayers#1274](https://github.com/bluefireteam/audioplayers/issues/1274)
> * [App crashes on mp3 play even with try/catch bluefireteam/audioplayers#1260](https://github.com/bluefireteam/audioplayers/issues/1260)
> 
> Closing this because I don't think there is anything that `flame_simple_platformer` can do to solve this.

Ok thank you for your reply
